// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqlsVdYIKRi5zxqXlcH9cTgpokkl40Bto',
    appId: '1:910882897101:web:17d979c4beb57fd2b6bd84',
    messagingSenderId: '910882897101',
    projectId: 'service-motor-ppl',
    authDomain: 'service-motor-ppl.firebaseapp.com',
    databaseURL: 'https://service-motor-ppl-default-rtdb.firebaseio.com',
    storageBucket: 'service-motor-ppl.appspot.com',
    measurementId: 'G-0N5K61CPNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFOibFUOE8gCWcMIYtEjppixQuzP8-jU4',
    appId: '1:910882897101:android:d476998deffae5feb6bd84',
    messagingSenderId: '910882897101',
    projectId: 'service-motor-ppl',
    databaseURL: 'https://service-motor-ppl-default-rtdb.firebaseio.com',
    storageBucket: 'service-motor-ppl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Hke0amQvaU4xAMXgTEH8wnX7Rvy3eTk',
    appId: '1:910882897101:ios:e42a0a521f2eb87bb6bd84',
    messagingSenderId: '910882897101',
    projectId: 'service-motor-ppl',
    databaseURL: 'https://service-motor-ppl-default-rtdb.firebaseio.com',
    storageBucket: 'service-motor-ppl.appspot.com',
    androidClientId: '910882897101-jju5jko2hv95togfebbcrnr97afose85.apps.googleusercontent.com',
    iosClientId: '910882897101-os835oh9i36jcmlg2l8voo6uaki346co.apps.googleusercontent.com',
    iosBundleId: 'com.ppl4b.servicemotormobile.serviceMotorMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Hke0amQvaU4xAMXgTEH8wnX7Rvy3eTk',
    appId: '1:910882897101:ios:e42a0a521f2eb87bb6bd84',
    messagingSenderId: '910882897101',
    projectId: 'service-motor-ppl',
    databaseURL: 'https://service-motor-ppl-default-rtdb.firebaseio.com',
    storageBucket: 'service-motor-ppl.appspot.com',
    androidClientId: '910882897101-jju5jko2hv95togfebbcrnr97afose85.apps.googleusercontent.com',
    iosClientId: '910882897101-os835oh9i36jcmlg2l8voo6uaki346co.apps.googleusercontent.com',
    iosBundleId: 'com.ppl4b.servicemotormobile.serviceMotorMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqlsVdYIKRi5zxqXlcH9cTgpokkl40Bto',
    appId: '1:910882897101:web:c32848ad9b4577f4b6bd84',
    messagingSenderId: '910882897101',
    projectId: 'service-motor-ppl',
    authDomain: 'service-motor-ppl.firebaseapp.com',
    databaseURL: 'https://service-motor-ppl-default-rtdb.firebaseio.com',
    storageBucket: 'service-motor-ppl.appspot.com',
    measurementId: 'G-2Y4618H2PR',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDqlsVdYIKRi5zxqXlcH9cTgpokkl40Bto',
    appId: '1:910882897101:web:250c39d84e4a57b7b6bd84',
    messagingSenderId: '910882897101',
    projectId: 'service-motor-ppl',
    authDomain: 'service-motor-ppl.firebaseapp.com',
    databaseURL: 'https://service-motor-ppl-default-rtdb.firebaseio.com',
    storageBucket: 'service-motor-ppl.appspot.com',
    measurementId: 'G-RCRF7V5G86',
  );
}
